name: Continuous Deployment
on:
  push:
    branches:
      - main
      - alpha
jobs:
  deploy:
    name: Deploy changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check formatting
        run: yarn prettier:check

      - name: Lint codebase
        run: yarn lint

      - name: Check types
        run: yarn typecheck

      - name: Test codebase
        run: yarn test

      - name: Build library
        run: yarn build

      - name: Release on NPM
        run: yarn semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
